---
version: "3.7"

services:
  umami:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.umami.loadbalancer.server.port=3000
      - traefik.http.routers.umami.entrypoints=web
      - traefik.http.routers.umami.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.umami-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.umami.middlewares=umami-https-redirect
      - traefik.http.routers.umami-secure.entrypoints=websecure
      - traefik.http.routers.umami-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.umami-secure.tls=true
      - traefik.http.routers.umami-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
